'use client';
import * as React from 'react';
import { Bell, Search } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Input } from '@cardioline/ui';
export function Header({ sidebarHidden = false }: { sidebarHidden?: boolean }) {
  const router = useRouter(); const [query,setQuery] = React.useState(''); const [open,setOpen] = React.useState(false);
  return <header className="relative flex h-16 w-full items-center justify-between border-b border-gray-200 bg-white px-6"><form className={`flex flex-1 items-center ${sidebarHidden ? 'pl-10' : ''}`} onSubmit={(event)=>{event.preventDefault();router.push(`/patients?q=${encodeURIComponent(query)}`)}}><div className="relative w-full max-w-md"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><Input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search patients, exams, or ID..." className="w-full border-gray-200 bg-gray-50 pl-10 focus-visible:ring-[#ee5b00]" /></div></form><div className="flex items-center"><button onClick={()=>setOpen(!open)} aria-expanded={open} className="relative rounded-full p-2 text-gray-400 hover:bg-gray-50 hover:text-gray-500"><span className="sr-only">View notifications</span><Bell className="h-5 w-5" /><span className="absolute right-1.5 top-1.5 block h-2 w-2 rounded-full bg-primary ring-2 ring-white" /></button></div>{open&&<div className="absolute right-6 top-14 z-30 w-80 rounded-lg border border-gray-200 bg-white p-2 shadow-xl"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-wide text-gray-400">Notifications</p><button onClick={()=>{setOpen(false);router.push('/exams')}} className="w-full rounded-md px-3 py-3 text-left text-sm hover:bg-orange-50"><strong className="block text-gray-900">1 exam needs review</strong><span className="text-xs text-gray-500">Jane Smith · Holter 24h</span></button><button onClick={()=>{setOpen(false);router.push('/exams')}} className="w-full rounded-md px-3 py-3 text-left text-sm hover:bg-orange-50"><strong className="block text-red-700">Critical result detected</strong><span className="text-xs text-gray-500">Robert Johnson · Stress Test</span></button></div>}</header>;
}
