'use client';

import * as React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { FileText, MoreVertical, Pencil, Plus, Search } from 'lucide-react';
import { Button, Card, CardContent, Input } from '@cardioline/ui';
import { exams, reports } from '@/lib/mock-data';
import { TablePagination } from '@/components/ui/table-pagination';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { SortableHeader, type SortDirection } from '@/components/ui/sortable-header';

type Patient = { id: string; name: string; dob: string; status: string; lastExam: string };

export function PatientDetailView({ patient }: { patient: Patient }) {
  const [page, setPage] = React.useState(1);
  const [pageSize, setPageSize] = React.useState(10);
  const [sort, setSort] = React.useState<{ key: 'date' | 'type' | 'result'; direction: SortDirection }>({ key: 'date', direction: 'desc' });
  const patientExams = exams.filter((exam) => exam.patientId === patient.id).sort((a, b) => { const result = String(a[sort.key]).localeCompare(String(b[sort.key]), undefined, { numeric: true }); return sort.direction === 'asc' ? result : -result; });
  const pageCount = Math.max(1, Math.ceil(patientExams.length / pageSize));
  const current = patientExams.slice((page - 1) * pageSize, page * pageSize);
  const [firstName, ...lastName] = patient.name.split(' ');
  const toggleSort = (key: 'date' | 'type' | 'result') => { setSort((current) => current.key === key ? { key, direction: current.direction === 'asc' ? 'desc' : 'asc' } : { key, direction: 'asc' }); setPage(1); };

  return <div className="space-y-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-gray-600">Patients <span className="px-1 text-gray-400">›</span> Patient details</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#071046]">{patient.name}</h1></div><div className="flex items-center gap-2"><Button asChild variant="secondary" className="h-11 px-5"><Link href={`/patients/${patient.id}/edit`}><Pencil className="mr-2 h-4 w-4" />Edit patient</Link></Button><PatientMoreMenu patientId={patient.id} /></div></div>

    <Card className="border-gray-200 bg-white shadow-sm"><CardContent className="p-7"><div className="grid gap-x-16 gap-y-6 md:grid-cols-2 lg:max-w-4xl lg:grid-cols-3"><Info label="First name" value={firstName} /><Info label="Last name" value={lastName.join(' ') || '—'} /><Info label="Patient ID" value={patient.id.replace('P-', '433977')} /><Info label="Second ID" value="43397744" /><Info label="E-mail" value={`${patient.name.toLowerCase().replaceAll(' ', '')}@email.com`} /><Info label="Phone" value="0362 209391012" /><Info label="Birthdate" value={patient.dob} /><Info label="Ethnicity" value="White" /><Info label="Gender" value="Male" /><Info label="Age" value="46 years" /><Info label="Address" value="Via Linz Spini di Gardolo, 151, 38121" className="md:col-span-2" /></div></CardContent></Card>

    <section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-[#071046]">Exam list</h2><p className="mt-1 text-sm text-gray-500">All diagnostic exams associated with this patient.</p></div><Button asChild className="bg-primary text-white"><Link href="/exams/ECG-2401">New ECG</Link></Button></div><Card className="border-gray-200 bg-white shadow-sm"><CardContent className="p-0"><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-600"><tr><th className="px-5 py-4"><SortableHeader label="Time of reception" active={sort.key === 'date'} direction={sort.direction} onClick={() => toggleSort('date')} /></th><th className="px-5 py-4"><SortableHeader label="Exam type" active={sort.key === 'type'} direction={sort.direction} onClick={() => toggleSort('type')} /></th><th className="px-5 py-4"><SortableHeader label="Summary" active={sort.key === 'result'} direction={sort.direction} onClick={() => toggleSort('result')} /></th><th className="px-5 py-4">Confirmed by</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{current.map((exam) => { const report = reports.find((item) => item.examId === exam.id); return <tr key={exam.id} className="cursor-pointer transition-colors hover:bg-orange-50/70"><td title={exam.date} className="px-5 py-4 font-medium text-slate-700"><Link href={`/exams/${exam.id}`} className="block">{exam.date}</Link></td><td title={exam.type} className="px-5 py-4 text-slate-700"><Link href={`/exams/${exam.id}`} className="block">{exam.type}</Link></td><td title={exam.result} className="px-5 py-4"><ResultBadge value={exam.result} /></td><td title="Dr. Sarah Jenkins" className="px-5 py-4 text-slate-600">Dr. Sarah Jenkins</td><td className="px-5 py-4 text-right"><div className="flex justify-end gap-1"><Button asChild size="icon" variant="ghost" aria-label={`View ${exam.id}`}><Link href={`/exams/${exam.id}`}><Search /></Link></Button>{report ? <Button asChild size="icon" variant="ghost" aria-label={`View report for ${exam.id}`}><Link href={`/reports/${report.id}`}><FileText /></Link></Button> : <Button size="icon" variant="ghost" disabled aria-label="Report not available"><FileText /></Button>}</div></td></tr>; })}</tbody></table>{!current.length && <p className="p-10 text-center text-sm text-gray-500">No exams are associated with this patient yet.</p>}</div><TablePagination page={page} pageCount={pageCount} total={patientExams.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(nextPageSize) => { setPageSize(nextPageSize); setPage(1); }} /></CardContent></Card></section>
  </div>;
}

function Info({ label, value, className = '' }: { label: string; value: string; className?: string }) { return <div className={className}><dt className="text-sm text-slate-600">{label}</dt><dd className="mt-1 font-semibold text-slate-700">{value}</dd></div>; }
function ResultBadge({ value }: { value: string }) { const cls = value === 'Normal' ? 'bg-emerald-100 text-emerald-700' : value === 'Abnormal' ? 'bg-red-100 text-red-700' : value === 'Borderline' ? 'bg-amber-100 text-amber-700' : 'bg-slate-100 text-slate-600'; return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${cls}`}>{value}</span>; }
function PatientMoreMenu({ patientId }: { patientId: string }) { const router = useRouter(); const [open, setOpen] = React.useState(false); const [confirmDelete, setConfirmDelete] = React.useState(false); return <div className="relative"><Button type="button" size="icon" variant="secondary" aria-label="Patient actions" onClick={() => setOpen(!open)}><MoreVertical /></Button>{open && <div className="absolute right-0 top-12 z-30 w-44 rounded-lg border border-gray-200 bg-white p-1 shadow-xl"><Link href={`/patients/${patientId}`} className="flex items-center gap-2 rounded-md px-3 py-2 text-sm hover:bg-gray-50">View patient</Link><Link href={`/patients/${patientId}/edit`} className="flex items-center gap-2 rounded-md px-3 py-2 text-sm hover:bg-gray-50">Edit patient</Link><button type="button" onClick={() => { setOpen(false); setConfirmDelete(true); }} className="w-full rounded-md px-3 py-2 text-left text-sm text-red-600 hover:bg-red-50">Delete patient</button></div>}<ConfirmDialog open={confirmDelete} title="Delete Patient" description="Are you sure you want to delete this patient? This action is permanent and the data cannot be recovered." onCancel={() => setConfirmDelete(false)} onConfirm={() => router.push('/patients')} /></div>; }
