'use client';

import { useRouter } from 'next/navigation';
import { Button, Card, CardContent, Input, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@cardioline/ui';

type PatientFormProps = { mode: 'create' | 'edit'; patientId?: string; patientName?: string };
const personalFields = [['first-name', 'First name (mandatory)', 'Type here', 'text', true], ['last-name', 'Last name', 'Type here', 'text', false], ['phone', 'Phone', 'Type here', 'tel', false], ['patient-id', 'Patient ID', 'Type here', 'text', false], ['patient-id-2', 'Patient ID 2', 'Type here', 'text', false], ['email', 'Email', 'Type here', 'email', false], ['birthday', 'Birthday', 'dd/mm/yy', 'text', false], ['ethnicity', 'Ethnicity', 'Type here', 'text', false]] as const;
const locationFields = [['address', 'Address', 'Type here'], ['city', 'City', 'Type here'], ['province', 'Province', 'dd/mm/yy'], ['region', 'Region', 'Type here'], ['country', 'Country', 'Type here']] as const;

export function PatientForm({ mode, patientId = 'P-10029', patientName = 'Andrea Gallo' }: PatientFormProps) {
  const router = useRouter(); const editing = mode === 'edit'; const [firstName = '', ...lastName] = patientName.split(' ');
  const values: Record<string, string> = editing ? { 'first-name': firstName, 'last-name': lastName.join(' '), phone: '0362 209391012', 'patient-id': patientId, 'patient-id-2': '43397744', email: `${patientName.toLowerCase().replaceAll(' ', '')}@email.com`, birthday: '05/02/1982', ethnicity: 'White', address: 'Via Linz Spini di Gardolo, 151', city: 'Gardolo', province: 'Trento', region: 'Trentino-Alto Adige', country: 'Italy' } : {};
  const destination = editing ? `/patients/${patientId}` : '/patients/P-10029';
  return <form onSubmit={(event) => { event.preventDefault(); router.push(destination); }} className="space-y-7"><div><p className="text-sm font-medium text-gray-700">Patients <span className="px-1 text-gray-400">›</span> {editing ? 'Edit Patient' : 'Add Patient'}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#071046]">{editing ? 'Edit Patient' : 'Create Patient'}</h1></div><Card className="border-gray-200 bg-white shadow-sm"><CardContent className="p-7"><h2 className="mb-7 text-base font-bold text-gray-900">Personal Info</h2><div className="grid gap-x-11 gap-y-6 md:grid-cols-2 xl:grid-cols-3">{personalFields.map(([id, label, placeholder, type, required]) => <Field key={id} id={id} label={label} placeholder={placeholder} type={type} required={required} value={values[id]} />)}<div className="space-y-2"><Label htmlFor="gender">Gender</Label><Select name="gender" defaultValue={editing ? 'Male' : undefined}><SelectTrigger id="gender" className="h-10 w-full"><SelectValue placeholder="Select an option" /></SelectTrigger><SelectContent>{['Female', 'Male', 'Other', 'Not specified'].map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select></div></div></CardContent></Card><Card className="border-gray-200 bg-white shadow-sm"><CardContent className="p-7"><h2 className="mb-7 text-base font-bold text-gray-900">Location Information</h2><div className="grid gap-x-11 gap-y-6 md:grid-cols-2 xl:grid-cols-3">{locationFields.map(([id, label, placeholder]) => <Field key={id} id={id} label={label} placeholder={placeholder} value={values[id]} />)}</div></CardContent></Card><div className="flex justify-end gap-3 pb-3"><Button type="button" variant="secondary" onClick={() => router.back()}>Cancel</Button><Button type="submit" className="bg-primary text-white">{editing ? 'Save changes' : 'Create patient'}</Button></div></form>;
}
function Field({ id, label, placeholder, type = 'text', required = false, value }: { id: string; label: string; placeholder: string; type?: string; required?: boolean; value?: string }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} type={type} required={required} defaultValue={value} placeholder={placeholder} className="h-10 border-gray-200 bg-white placeholder:text-gray-400 focus-visible:ring-[#ee5b00]" /></div>; }
