'use client';

import * as React from 'react';
import Link from 'next/link';
import { Download, FileText, Search } from 'lucide-react';
import { Button, Card, CardContent, Input } from '@cardioline/ui';
import { reports } from '@/lib/mock-data';
import { SortableHeader, type SortDirection } from '@/components/ui/sortable-header';

type SortKey = 'id' | 'patient' | 'date' | 'status';
export default function ReportsPage() {
  const [query, setQuery] = React.useState(''); const [sort, setSort] = React.useState<{ key: SortKey; direction: SortDirection }>({ key: 'date', direction: 'desc' });
  const list = reports.filter((report) => `${report.patient} ${report.type} ${report.id}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => { const result = String(a[sort.key]).localeCompare(String(b[sort.key]), undefined, { numeric: true }); return sort.direction === 'asc' ? result : -result; });
  const toggleSort = (key: SortKey) => setSort((current) => current.key === key ? { key, direction: current.direction === 'asc' ? 'desc' : 'asc' } : { key, direction: 'asc' });
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold tracking-tight text-[#071046]">Reports</h1><p className="mt-1 text-sm text-gray-500">Generated medical reports and findings.</p></div><Card className="border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 p-4"><div className="relative max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><Input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reports..." className="border-gray-200 bg-gray-50 pl-9" /></div></div><CardContent className="p-0"><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr><th className="px-6 py-4"><SortableHeader label="Report" active={sort.key === 'id'} direction={sort.direction} onClick={() => toggleSort('id')} /></th><th className="px-6 py-4"><SortableHeader label="Patient" active={sort.key === 'patient'} direction={sort.direction} onClick={() => toggleSort('patient')} /></th><th className="px-6 py-4"><SortableHeader label="Generated" active={sort.key === 'date'} direction={sort.direction} onClick={() => toggleSort('date')} /></th><th className="px-6 py-4"><SortableHeader label="Status" active={sort.key === 'status'} direction={sort.direction} onClick={() => toggleSort('status')} /></th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{list.map((report) => <tr key={report.id} className="cursor-pointer transition-colors hover:bg-orange-50/70"><td className="px-6 py-4"><Link href={`/reports/${report.id}`} className="flex items-center gap-3 font-medium text-gray-900"><FileText className="h-4 w-4 text-[#ee5b00]" />{report.type}<span className="text-xs font-normal text-gray-400">{report.id}</span></Link></td><td className="px-6 py-4 text-gray-700"><Link href={`/reports/${report.id}`} className="block">{report.patient}</Link></td><td className="px-6 py-4 text-gray-500"><Link href={`/reports/${report.id}`} className="block">{report.date}</Link></td><td className="px-6 py-4"><Status status={report.status} /></td><td className="px-6 py-4"><div className="flex justify-end gap-2"><Button asChild size="sm" variant="outline"><Link href={`/reports/${report.id}`}>View</Link></Button><Button asChild size="icon" variant="ghost" aria-label={`Download ${report.id}`} className="text-[#ee5b00]"><a href={`/api/reports/${report.id}`} download><Download /></a></Button></div></td></tr>)}</tbody></table>{!list.length && <p className="p-10 text-center text-sm text-gray-500">No reports match this search.</p>}</div></CardContent></Card></div>;
}
function Status({ status }: { status: string }) { const cls = status === 'Finalized' ? 'bg-green-100 text-green-700' : status === 'Pending Review' ? 'bg-orange-100 text-orange-700' : 'bg-gray-100 text-gray-700'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${cls}`}>{status}</span>; }
