'use client';

import { Settings2 } from 'lucide-react';
import { Button, Checkbox, DropdownMenu, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@cardioline/ui';

export type TableDensity = 'compact' | 'comfortable' | 'spacious';
export type TableColumnSetting = { id: string; label: string; locked?: boolean };

export function TableSettingsMenu({ columns, visibleColumns, onVisibleColumnsChange, density, onDensityChange }: { columns: TableColumnSetting[]; visibleColumns: string[]; onVisibleColumnsChange: (columns: string[]) => void; density: TableDensity; onDensityChange: (density: TableDensity) => void }) {
  const toggleColumn = (id: string) => onVisibleColumnsChange(visibleColumns.includes(id) ? visibleColumns.filter((column) => column !== id) : [...visibleColumns, id]);
  return <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="outline" aria-label="Table settings" className="shrink-0"><Settings2 /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-[23rem] p-0"><DropdownMenuLabel className="px-5 py-4 text-sm normal-case tracking-normal text-foreground">Table settings</DropdownMenuLabel><DropdownMenuSeparator /><div className="px-5 py-5"><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Row density</p><div className="flex flex-wrap gap-2">{(['compact', 'comfortable', 'spacious'] as const).map((option) => <button key={option} type="button" onClick={() => onDensityChange(option)} className={`rounded-full border px-3.5 py-2 text-xs font-semibold capitalize transition-colors ${density === option ? 'border-orange-200 bg-orange-50 text-[#ee5b00]' : 'border-border bg-background text-foreground hover:border-orange-200 hover:bg-orange-50'}`}>{option}</button>)}</div></div><DropdownMenuSeparator /><div className="px-5 py-5"><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Visible columns</p><div className="grid gap-2 sm:grid-cols-2">{columns.map((column) => <label key={column.id} className={`flex min-h-11 items-center gap-2 rounded-md border px-3 py-2 text-sm transition-colors ${column.locked ? 'cursor-not-allowed border-slate-100 bg-slate-50 text-muted-foreground' : 'cursor-pointer border-slate-200 text-foreground hover:border-orange-200 hover:bg-orange-50/50'}`}><Checkbox checked={column.locked || visibleColumns.includes(column.id)} disabled={column.locked} onCheckedChange={() => !column.locked && toggleColumn(column.id)} /><span className="min-w-0 flex-1 truncate">{column.label}</span>{column.locked && <span className="text-[10px] font-medium uppercase tracking-wide">Required</span>}</label>)}</div></div></DropdownMenuContent></DropdownMenu>;
}
